name = "MailerSend"
nameId = "mailersend"
categories = ["email"]
version = "0.0.3-alpha"
logo = "https://raw.githubusercontent.com/BusinessQL/businessql-app-mailersend/main/images/logo.svg"

[settings]
  [[settings.fields]]
  label = "API Key"
  name = "apiKey"
  type = "password"

  [[settings.fields]]
  label = "From email"
  name = "from"
  type = "text"

[developer]
nameId = "businessql"

[theme.colors]
primary = "#4E48E0"
